### PR TITLE
feat(cri-registry-auth): add criRegistryAuth to localstack

### PR DESCRIPTION
**Pull request by kty1965**
First,
I need to execute lambda by private container registry with auth.

criRegistryAuth config can enabled/disabled.

And you need to set your private registry credentials.

Second,
Lambda EXECUTOR with dind need to main container name & docker_host config.

### CODE REVIEW

**Comment by whummer** [comment]
Thanks for this PR @kty1965 . There's quite a few changes in here - can you please add a short summary of the changes, and how they relate to each other? Thanks!

**Comment by kty1965** [comment]
@whummer 👋 hello, I edited my description on PR.
Please checkout!

**Comment by alexrashed** [comment]
Hi @kty1965!
Sorry for the late response. This PR would change quite a lot, where I'm missing the context a bit to be honest.
These changes are quite specific to your use-case. Is there a chance to find a more generic solution to your problem?

**Comment by alexrashed** [comment]
I'll close this PR for now due to inactivity. Please let us know if you would like to revamp it. Thanks!

**Pull request closed without merging**
