### PR TITLE
Add Custom Annotations Block to Service

### PR DESCRIPTION
**Pull request by LaikaN57**
This is a follow up to https://github.com/localstack/helm-charts/pull/48. We are simply adding an annotations block to the service resource as we did in the ingress resource.

### CODE REVIEW

**Comment by LaikaN57** [comment]
cc: @saansh45

**Comment by LaikaN57** [comment]
cc: @whummer (Looks like you were the approver for #48.)

**Review by saansh45 — APPROVED** [review]
LGTM 👍

**Review by whummer — APPROVED** [review]
LGTM, thanks @LaikaN57 ! 👍

**Pull request merged**
